// This file is generated by Prismic local builder. Update with care!

export { default as CallToAction } from './CallToAction'
export { default as Image } from './Image'
export { default as ImageGallery } from './ImageGallery'
export { default as Text } from './Text'
export { default as TextImage } from './TextImage'
